version: '3'

services:
  mysqlsvr:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 3
      interval: 5s
    # volumes:
    #   - db_data:/var/lib/mysql
    networks:
        - webapp-network

  djangoapp:
    restart: always
    build: ./
    expose:
      - "8000"
    volumes:
      - ./web:/usr/src/app
      - web-static:/usr/src/app/static
    links:
      - mysqlsvr
    depends_on:
      mysqlsvr:
          condition: service_healthy
    networks:
        - webapp-network
    working_dir: /usr/src/app
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn foodtasker.wsgi:application --bind 0.0.0.0:8000"
    
  webserver:
    image: nginx:latest
    container_name: webserver
    ports:
        - "8080:80"
    volumes:
        - web-static:/www/static
        - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
        - webapp-network
    links:
        - djangoapp
    depends_on:
        - mysqlsvr
        - djangoapp
    volumes_from:
        - djangoapp

networks:
    webapp-network:
        driver: bridge
volumes:
    web-static:        
        